---
# tasks file for ansible-telegraf

- name: Download the package for ubuntu
  get_url:
    url: http://dl.influxdata.com/telegraf/releases/telegraf_{{ telegraf_agent_version }}_amd64.deb
    dest: /tmp/telegraf_{{ telegraf_agent_version }}_amd64.deb
  when: ansible_os_family == "Debian"

- name: Install the package for ubuntu
  apt: 
    deb: /tmp/telegraf_{{ telegraf_agent_version }}_amd64.deb
  when: ansible_os_family == "Debian"

- name: Download the package for Centos
  get_url:
    url: http://dl.influxdata.com/telegraf/releases/telegraf-{{ telegraf_agent_version }}.x86_64.rpm
    dest: /tmp/telegraf-{{ telegraf_agent_version }}.x86_64.rpm
  when: ansible_os_family == "RedHat"

- name: Install the package for Centos
  command: yum localinstall -y /tmp/telegraf-{{ telegraf_agent_version }}.x86_64.rpm
  changed_when: False
  when: ansible_os_family == "RedHat"

- name: Install sysstat for ubuntu
  apt:
    name: sysstat
    state: present
  when: ansible_os_family == "Debian"

- name: Install sysstat for Centos
  yum:
    name: sysstat
    state: present
  when: ansible_os_family == "RedHat"

- name: Copy the template
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: telegraf
    group: telegraf
    mode: 0644

- name: restart telegraf
  sudo: True
  monit:
    name: telegraf
    state: restarted
  ignore_errors: yes
